name: PerInfo
version: '1.2'
main: com.comonier.perinfo.PerInfo
api-version: '1.21'
description: Advanced utility for permissions and interactive chat symbols.
author: Comonier

softdepend: [Vault, VentureChat, EssentialsChat, LPC]

commands:
  per:
    description: "PerInfo Tutorial."
    usage: "/per"
  perinfo:
    description: "Main Command."
    usage: "/perinfo <comando|reload>"
    permission: perinfo.use
  iinfo:
    description: "Show Item ID"
    usage: "/iinfo"
    permission: perinfo.iinfo

permissions:
  perinfo.use:
    description: "Use /perinfo, /per Command list."
    default: true
  perinfo.iinfo:
    description: "Use /iinfo command Item ID."
    default: true
  perinfo.chat:
    description: "Link permission [hand], [INV], [EC], etc."
    default: true
