name: PerInfo
version: '1.2'
main: com.comonier.perinfo.PerInfo
api-version: '1.21'
description: Advanced utility for permissions and interactive chat symbols.
author: Comonier

softdepend: [Vault, VentureChat, EssentialsChat, LPC]

commands:
  per:
    description: "Guia de comandos e símbolos do PerInfo."
    usage: "/per"
  perinfo:
    description: "Comando principal para lookup de plugins e comandos internos."
    usage: "/perinfo <comando|reload>"
    permission: perinfo.use
  iinfo:
    description: "Mostra detalhes técnicos do item na mão."
    usage: "/iinfo"
    permission: perinfo.iinfo

permissions:
  perinfo.use:
    description: "Permite usar o lookup de comandos."
    default: op
  perinfo.iinfo:
    description: "Permite inspecionar itens."
    default: op
  perinfo.chat:
    description: "Permite usar os símbolos [hand], [INV], [EC], etc."
    default: true
